### ISSUE TITLE
Some test cases failed for convolution backward data when set compute type to bf8 and f8

### ISSUE THREAD

**Issue by iq136boy** [ROCm/composable_kernel#1031]
Integrated the nf8/f8 convolution backward data solver into MIOpen. However, only some of the test cases can pass, the rest failed.
For example, the following example getting from the ck client example can pass the test:
g    n   c   d    h   w   k   z  y  x pad_x pad_y pad_z stri_x stri_y stri_z dia_x dia_y dia_z
 2, 16, 16, 14, 14, 14, 16, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1

The following one can not:
1, 128, 64, 1, 28, 28, 64, 1, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1

Could someone help to check the backward data kernels for bf8/f8 compute datatype? Thanks.

**Comment by geyyer** [comment]
Hi @iq136boy, thanks for reporting the issue! Which device did you test it on? Could you share the passing and failing tests?

**Comment by iq136boy** [comment]
> Hi @iq136boy, thanks for reporting the issue! Which device did you test it on? Could you share the passing and failing tests?

Hi @geyyer  One pass case and one failed test case have given when I open the issue. Please refer [here](https://github.com/ROCmSoftwarePlatform/composable_kernel/issues/1031#issue-1985985319)  I can give more test cases if needed.

The backward weight convolution kernel also does not work properly for f8/bf8 compute type using the test case that I have. Could you also help to check it? And could you also help to provide a client example or test case that can run backward weight kernel properly for f8/bf8 compute type? Thanks.

The forward convolution kernel works fine with the f8 compute type. All test cases passed.

All the tests are done on mi200 (gfx90a).

**Comment by geyyer** [comment]
Thanks for the input, @iq136boy! I'll try to reproduce the issue. Conv bwd weight client example is coming soon https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/1005

**Comment by geyyer** [comment]
Hi @iq136boy, I've played around with the cases you provided and here is the thing - dimension-wise it is not fair to use a convolution filter with {x, y, z} = {3, 3, 1}. If we set padding to {1, 1, 1}, the filter should be {3, 3, 3}. In such case dimensions match and example is executed correctly. Could you check it out and confirm if it works for you?

**Comment by iq136boy** [comment]
Hi @geyyer , thanks for the update. I use the 3d ck kernels to solve 2d cases, so the filter z should be 1. I set padding_z to 0 and it seems work fine for the backward data solver. However, the backward weight solver still does not work properly when set compute type to bfp8/fp8. Have you ever tried the backward weight kernel in CK? Do you have an example case that can run backward weight properly?

**Comment by geyyer** [comment]
@iq136boy, great to hear that bwd data works fine, good point regarding setting padding to 0! Regarding the bwd weight, the PR https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/1005 is already merged and this client example worked fine for me, please check it out!

**Comment by iq136boy** [comment]
> @iq136boy, great to hear that bwd data works fine, good point regarding setting padding to 0! Regarding the bwd weight, the PR #1005 is already merged and this client example worked fine for me, please check it out!

@geyyer Thanks for adding the client example for the backward weight. But it seems that the error of backward weight solver and naive solver is bigger than expected. I might need to reach out to you to discuss about it in detail.

**Comment by geyyer** [comment]
All related PRs are merged, tests look good, closing the issue.
