### ISSUE TITLE
GEMM specification not found in CK?

### ISSUE THREAD

**Issue by chengl-amd** [ROCm/composable_kernel#1034]
Hi there,

I am wondering which impl or example I can refer to if I want to run:

RELU(GEMM (A[M,K]_INT8, B[K,N]_INT8) + bias_INT8) = output_INT8.

I tried example/03_gemm_bias_relu, but it fails to build when I set:

using ADataType        = int8_t;
using BDataType        = int8_t;
using AccDataType      = F32;
using CShuffleDataType = F16;
using DDataType        = int8_t;
using EDataType        = int8_t;

KR

**Comment by bartekxk** [comment]
Hi @chengl-amd , try[ this branch ](https://github.com/ROCm/composable_kernel/tree/barkocot/relu-bias-int8) , I changed AccDataType and CShuffleDataType to `int32_t` (which is supported with `int8_t`).

**Comment by ppanchad-amd** [comment]
@chengl-amd Is your issue resolved? If so, please close the ticket. Thanks!

**Comment by ppanchad-amd** [comment]
@chengl-amd Closing ticket. Please re-open the ticket if you still see the issue with the latest ROCm. Thanks!
