### ISSUE TITLE
Bug: Filter1x1Stride1Pad0  and Filter1x1Pad0 

### ISSUE THREAD

**Issue by zslovelq** [ROCm/composable_kernel#1038]
files:
composable_kernel/include/ck/tensor_operation/gpu/device/impl/device_grouped_conv_fwd_multiple_d_multiple_r_xdl_cshuffle.hpp
composable_kernel/include/ck/tensor_operation/gpu/device/impl/device_grouped_conv_fwd_multiple_d_xdl_cshuffle.hpp

problems:
    In fuction "static bool IsSupportedArgument(const Argument& arg)" 
    "const index_t X          = arg.b_g_k_c_xs_lengths_[i + 2]; " 
     should be 
    "const index_t X          = arg.b_g_k_c_xs_lengths_[i + 3]; "
Each file has two wrong lines，so there are 4 wrong line in  these 2 files.

![image](https://github.com/ROCmSoftwarePlatform/composable_kernel/assets/71253756/807c1642-e2ab-4834-8738-a6d7eb78f8a4)

**Comment by bartekxk** [comment]
Thanks!
