### ISSUE TITLE
Duplicate kernel strings returned from FillValidKernelsIDs<DeviceOpGFwdPtrs<DataType>, CKArgs>(problem).

### ISSUE THREAD

**Issue by Dmantri98** [ROCm/composable_kernel#1041]
While testing the kernel parameter prediction model for the conv_hip_implicit_gemm_grouped_fwd_xdlops.cpp solver within MIOpen I discovered that there were duplicate kernel strings being returned from the FillValidKernelsIDs<DeviceOpGFwdPtrs<DataType>, CKArgs>(problem) function. The duplicate kernel strings were:
"DeviceGroupedConvFwdMultipleD_Xdl_CShuffle<64, 64, 32, 16, OddC, 32, 32, 2, 1, 4, 4, 1, 1>"
"DeviceGroupedConvFwdMultipleD_Xdl_CShuffle<64, 64, 32, 16, Default, 32, 32, 2, 1, 4, 4, 1, 1>".

There were two instances of each string within the list returned from the FillValidKernelsIDs function.

The MIOpen driver command I used to produce this issue:
./bin/MIOpenDriver conv --spatial_dim 2 --forw 1 --in_layout NHWC --in_channels 256 --in_h 312 --in_w 192 --out_layout NHWC --out_channels 12 --fil_layout NHWC --fil_h 1 --fil_w 1 --pad_h 0 --pad_w 0 --conv_stride_h 1 --conv_stride_w 1 --dilation_h 1 --dilation_w 1 --batchsize 2 --group_count 1 --solution 137 --verify 0 --iter 3 -t 1 -w 1

The docker tag for the image I was using was:
rocm/miopen:ci_2ad3bb.

The base MIOpen commit hash that I was working off of:
1b46196c9cb1e3bc6ab4bbd1354718d72b88a70a

**Comment by bartekxk** [comment]
Hi @Dmantri98, If I understand correctly there is no dupplication in:\
"DeviceGroupedConvFwdMultipleD_Xdl_CShuffle<64, 64, 32, 16, **OddC**, 32, 32, 2, 1, 4, 4, 1, 1>"
"DeviceGroupedConvFwdMultipleD_Xdl_CShuffle<64, 64, 32, 16, **Default**, 32, 32, 2, 1, 4, 4, 1, 1>".
There are two different specializations: OddC and Default.

**Comment by Dmantri98** [comment]
Hi @bartekxk, These two strings had duplicates in the returned list, as in there were two instances of each of these strings in the vector returned from the FillValidKernelsIDs<DeviceOpGFwdPtrs, CKArgs>(problem) function.

**Comment by bartekxk** [comment]
Thanks for explanation @Dmantri98 . You're right. #1042 should fix this problem
