### ISSUE TITLE
[Calling on cmake Experts] Keep interface consistent for other libraries which depends on CK

### ISSUE THREAD

**Issue by junliume** [ROCm/composable_kernel#1053]
https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/1044 propose to split up the library into smaller files (or else the size will exceed 4GB~)
```
libdevice_contraction_operations.a  libdevice_conv_operations.a  libdevice_gemm_operations.a  libdevice_other_operations.a  libdevice_reduction_operations.a  libutility.a
```
however, it will break other libraries which depends on stable interface with CK

https://github.com/ROCmSoftwarePlatform/hipTensor/blob/0b59b70357158b72032b83cb7644effb87505f70/library/src/CMakeLists.txt#L27

```
find_package( composable_kernel 1.0.0 REQUIRED PATHS /opt/rocm /opt/rocm/ck $ENV{CK_DIR}/lib/cmake COMPONENTS device_operations ) 
```

**[Question]**:
Can we make `${CK_DEVICE_OPERATIONS}` to include the list of `*.a` files above, so that other libraries can use `CK_DEVICE_OPERATIONS` instead of hard coded names? Is it feasible?

Another smaller issue:

When CK is installed, the `config.h.in` and `version.h.in` files are also installed into `/opt/rocm/include/ck` directory. Could someone also take a look to prevent it?

**Comment by junliume** [comment]
relate to https://github.com/ROCmSoftwarePlatform/hipTensor/issues/153

**Comment by pfultz2** [comment]
> Can we make ${CK_DEVICE_OPERATIONS} to include the list of *.a files above, so that other libraries can use CK_DEVICE_OPERATIONS instead of hard coded names? Is it feasible?

There is no reason to make a cmake variable for this. Instead composable_kernel should provide a cmake interface target which will link all components:

```cmake
add_library(all_device_operations INTERFACE)
target_link_libraries(device_operations INTERFACE 
    device_contraction_operations
    device_conv_operations
    device_gemm_operations
    device_other_operations
    device_reduction_operations
    utility)
```

Then users can link all operations by doing `target_link_libraries(myLib composable_kernel::device_operations)`.

**Comment by illsilin** [comment]
I think this has been resolved, so we can close the issue.
