### ISSUE TITLE
3D Group Convolution BWD and Weight Update passes fail when pads and strides are not all 1s

### ISSUE THREAD

**Issue by amberhassaan** [ROCm/composable_kernel#1070]
Please see https://github.com/ROCmSoftwarePlatform/MIOpen/pull/2560 

I will debug this further to establish if the fault lies on the MIOpen side, but opening this issue in case it's a CK bug. 

CC: @JehandadKhan , @junliume , @zjing14 , @iq136boy

**Comment by zjing14** [comment]
@bartekxk Could you take a look?

**Comment by bartekxk** [comment]
The problem was caused by a bug in MIOpen.

**Comment by junliume** [comment]
@bartekxk have we communicated the bug and whether it is fixed in MIOpen with @amberhassaan ?

**Comment by amberhassaan** [comment]
@junliume : Yes, @bartekxk helped me identify the issue (lengthy process of comparing things on MIOPen and CK sides) and I will cleanup my code and push a fix to MIOpen PR 2560 referenced in the description.

**Comment by atamazov** [comment]
FYI https://github.com/ROCm/MIOpen/pull/2373/files#r1425955983

**Comment by bartekxk** [comment]
@atamazov Good point
