### ISSUE TITLE
Fused Op `ScaleAddScaleAddRelu` assumes that bias has the same shape as output. 

### ISSUE THREAD

**Issue by amberhassaan** [ROCm/composable_kernel#1076]
See https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/bc4bf9bd03a74aba1860b80fbeb85fb1f47b8b19/client_example/23_grouped_convnd_fwd_scaleadd_scaleadd_relu/grouped_conv_fwd_scaleadd_scaleadd_relu.inc#L120-L121 

and PR: https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/1006 

the `bias` tensor is assumed to have the same size and layout as `output` and the residual tensor `z`. In MIOpen, `bias` is a vector of size `K`.  This needs to be fixed asap on the CK side IMO. 

CC: @JehandadKhan , @junliume , @zjing14

**Comment by bartekxk** [comment]
Hi @amberhassaan , please take a look at #1081 . Does this meet your requirements?
