### ISSUE TITLE
[WA] Remove workaround after next compiler staging

### ISSUE THREAD

**Issue by junliume** [ROCm/composable_kernel#1078]
https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/1077/files

These workarounds should be removed after next compiler staging

ETA: 12/15

**Comment by bartekxk** [comment]
Hi @junliume , can You confirm that staging is completed?

**Comment by junliume** [comment]
@bartekxk @zjing14 it seem not ... please track https://ontrack-internal.amd.com/browse/SWDEV-435347

**Comment by junliume** [comment]
Patch is in http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/13234/
