### ISSUE TITLE
CMake options are not defined correctly

### ISSUE THREAD

**Issue by GZGavinZhao** [ROCm/composable_kernel#1111]
In the declaration of the two CMake options `USE_BITINT_EXTENSION_INT4` and `USE_OPT_NAVI3X` [here](https://github.com/ROCm/composable_kernel/blob/20b1ae7cedcab951ff9499d5cf812176cf71b7e4/CMakeLists.txt#L182), there's an extra comma after the definition, causing the options to be actually named as `USE_BITINT_EXTENSION_INT4,` and `USE_OPT_NAVI3X,`.

This doesn't cause any build issues because the default for these values are OFF, and when we turn them on with the command-line we obviously don't type the option names followed by a comma, but for clarity sake I think this typo should be fixed.

**Comment by illsilin** [comment]
Yeah, thanks for spotting this. I'll fix it.

**Comment by illsilin** [comment]
Fixed.
