### ISSUE TITLE
[Issue]: ROCm/xformer won't compile due to missing ck/tensor/tensor_view.hpp

### ISSUE THREAD

**Issue by lhl** [ROCm/composable_kernel#1171]
### Problem Description

I have a 7900XTX (RDNA3, navi3, gfx1100) card that I'm trying to do some useful LLM work and one of the requirements I have is xformers. I am trying to build the https://github.com/ROCm/xformers/tree/develop fork. It depends on composable_kernel, but when building, it fails because it's looking for a file that doesn't seem to exist (and search doesn't seem to turn anything up either):  

xformers/xformers/csrc/attention/hip_fmha/ck_tiled_fmha_batched_forward_hip.h:16:10: fatal error: 'ck/tensor/tensor_view.hpp' file not found
#include <ck/tensor/tensor_view.hpp>

Just wondering if there's a branch I missed that I should be using instead or some other way to get xformers compiling w/ ck?

### Operating System

Ubuntu 22.04.3 LTS

### CPU

AMD Ryzen 5800X3D

### GPU

AMD Radeon RX 7900 XTX

### ROCm Version

ROCm 6.0.0

### Steps to Reproduce

```
git clone https://github.com/ROCm/xformers
cd xformers
git fetch
git branch -a
git checkout develop
git submodule update --init --recursive
python setup.py install
```

**Comment by hackey** [comment]
Dear developers. I support the question. Tell me, is it possible to use xformers with composable_kernel (or without composable_kernel) with a 7900 xtx video card?

**Comment by ppanchad-amd** [comment]
@lhl Apologies for the delayed response. Internal ticket has been created to assist with your issue. Thanks!

**Comment by alexxu-amd** [comment]
@lhl @hackey,

Currently, xformers on ROCm only works with MI200/MI300. So unfortunately, 7900 XTX won't be able to run it at the moment. Apologize for the inconvenience.

**Comment by lhl** [comment]
> @lhl @hackey Currently, xformers on ROCm only works with MI200/MI300. So unfortunately, 7900 XTX won't be able to run it at the moment. Apologize for the inconvenience.

OK, thanks for the followup. I know at some point @danielhanchen was chatting w/ some people at AMD a few months back as well, but lack of xformers is I believe the big blocker for [unsloth](https://github.com/unslothai/unsloth) support.

If it matters to anyone up the chain, feedback that RDNA3 would be significantly more useful if xformers were supported. (I know AMD has been trying to push the W7900 as an AI/ML dev/workstation card, but RDNA3 support is poor across the board, not just xformers!)

**Comment by unclemusclez** [comment]
i dont know if this works, but it installed: https://github.com/EmbeddedLLM/xformers-rocm
`pip install git+https://github.com/EmbeddedLLM/xformers-rocm.git`

you can also install `xformers` directly from the pytorch website

**Comment by arunhk3** [comment]
> i dont know if this works, but it installed: https://github.com/EmbeddedLLM/xformers-rocm `pip install git+https://github.com/EmbeddedLLM/xformers-rocm.git`
> 
> you can also install `xformers` directly from the pytorch website

Actually this worked :) But we need to remove triton though as it was causing issues...
