### ISSUE TITLE
GemmSpecialization

### ISSUE THREAD

**Issue by xiaobo1025** [ROCm/composable_kernel#1179]
### Problem Description

Different matrix padding for CK, such as. 
GemmSpec = = GemmSpecialization::MKPadding. 
GemmSpec = = GemmSpecialization::NKPadding. 
GemmSpec = = GemmSpecialization::MNKPadding. 
GemmSpec = = GemmSpecialization::KPadding)). 
Will it have any effect on the original matrix?

### Operating System

e.g

### CPU

e.g

### GPU

AMD Instinct MI210

### ROCm Version

ROCm 6.0.0

### ROCm Component

Other

### Steps to Reproduce

e.g

### (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support

e.g

### Additional Information

e.g

**Comment by ppanchad-amd** [comment]
@xiaobo1025 Internal ticket has been created to assist with your question. Thanks!

**Comment by jamesxu2** [comment]
Hi @xiaobo1025 ,

The different padding strategies (```GemmSpecialization::*```) do not modify the original matrix. A tensor descriptor is used to coordinate reads from memory. Using a 2D tensor as an example:
- Reading from a point within M,K -> Read directly from memory
- Reading from a point outside M,K but within MPad, KPad -> Set register to 0, don't perform a load

An example can be found in this code block: https://github.com/ROCm/composable_kernel/blob/develop/include/ck/tensor_operation/gpu/grid/gridwise_gemm_xdl_cshuffle_v1.hpp#L218
