### ISSUE TITLE
int4 inverse quantization and gemm on existing templates

### ISSUE THREAD

**Issue by kahakuka** [ROCm/composable_kernel#1199]
Is it difficult for me to achieve the fusion of int4 inverse quantization and gem using the existing template? What suggestions do you have?

**Comment by zjing14** [comment]
HIP does not support sub-byte data types. Are you using int4x2?

**Comment by kahakuka** [comment]
@zjing14 Thank you for your answer.Not use int4x2.It quantifies fp16 into int4 according to a certain pattern and stores it in a uint32 type.The paper introduces it this way.
![image](https://github.com/ROCm/composable_kernel/assets/40659418/3823dafb-d2d4-444d-acd6-7edd5bf104f6)

**Comment by kahakuka** [comment]
@zjing14 
Is it easy to implement the integration of int4+gemm on composable_kernel by referring to the method of mma in llm-awq?

llm-awq：The processing of int4 dequation can refer to this file.
https://github.com/mit-han-lab/llm-awq/blob/main/awq/kernels/csrc/quantization_new/dequantize.cuh

**Comment by huanrwan-amd** [comment]
@xiabo123 Can you provide more context about your request? what do you intend to do for your project? If you have code snippet   to share that would be helpful.

**Comment by huanrwan-amd** [comment]
Closed issue as no updates for 3 weeks.
