### ISSUE TITLE
[Issue]: What exactly does example_gemm_xdl_fp16 do?

### ISSUE THREAD

**Issue by deeplearningapps** [ROCm/composable_kernel#1215]
### Problem Description

I get much higher performance than I do with ckProfiler.
Is this just some sort of CU-level unit test?

### Operating System

Ubuntu 22.04

### CPU

AMD

### GPU

AMD Instinct MI250

### ROCm Version

ROCm 6.0.0

### ROCm Component

Composable Kernel

**Comment by zjing14** [comment]
Could you post your steps and gemm cases for reproduction?

**Comment by ppanchad-amd** [comment]
@deeplearningapps Closing ticket as there is no response. If you still require assistance with this ticket, please re-open the ticket. Thanks!
