### ISSUE TITLE
compile error use ck_tile in fmha on develop branch

### ISSUE THREAD

**Issue by flyingdown** [ROCm/composable_kernel#1288]
```
cd /root/flash-attention/composable_kernel-develop/build/example/ck_tile/01_fmha && /opt/conda/bin/python3.8 /root/flash-attention/composable_kernel-develop/example/ck_tile/01_fmha/generate.py --output_dir /root/flash-attention/composable_kernel-develop/build/example/ck_tile/01_fmha
cd /root/flash-attention/composable_kernel-develop/build && /opt/conda/bin/cmake -E cmake_depends "Unix Makefiles" /root/flash-attention/composable_kernel-develop /root/flash-attention/composable_kernel-develop/example/ck_tile/01_fmha /root/flash-attention/composable_kernel-develop/build /root/flash-attention/composable_kernel-develop/build/example/ck_tile/01_fmha /root/flash-attention/composable_kernel-develop/build/example/ck_tile/01_fmha/CMakeFiles/tile_example_fmha_fwd.dir/DependInfo.cmake --color=
make[3]: Leaving directory '/root/flash-attention/composable_kernel-develop/build'
make  -f example/ck_tile/01_fmha/CMakeFiles/tile_example_fmha_fwd.dir/build.make example/ck_tile/01_fmha/CMakeFiles/tile_example_fmha_fwd.dir/build
make[3]: Entering directory '/root/flash-attention/composable_kernel-develop/build'
[  0%] Building CXX object example/ck_tile/01_fmha/CMakeFiles/tile_example_fmha_fwd.dir/fmha_fwd.cpp.o
cd /root/flash-attention/composable_kernel-develop/build/example/ck_tile/01_fmha && /opt/rocm/bin/hipcc -DCK_ENABLE_BF16 -DCK_ENABLE_BF8 -DCK_ENABLE_FP16 -DCK_ENABLE_FP32 -DCK_ENABLE_FP64 -DCK_ENABLE_FP8 -DCK_ENABLE_INT8 -DCK_USE_XDL -D__HIP_PLATFORM_AMD__=1 -D__HIP_PLATFORM_HCC__=1 -I/root/flash-attention/composable_kernel-develop/library/include -I/root/flash-attention/composable_kernel-develop/include -I/root/flash-attention/composable_kernel-develop/build/include -I/root/flash-attention/composable_kernel-develop/example/ck_tile -I/root/flash-attention/composable_kernel-develop/example/ck_tile/01_fmha -Xclang -mllvm -Xclang -enable-post-misched=0 -std=c++17 -O3 -ftemplate-backtrace-limit=0  -fPIE  -Wno-gnu-line-marker -O3 -DNDEBUG -std=c++17   -Wall -Wextra -Wcomment -Wendif-labels -Wformat -Winit-self -Wreturn-type -Wsequence-point -Wswitch -Wtrigraphs -Wundef -Wuninitialized -Wunreachable-code -Wunused -Wno-reserved-identifier -Werror -Wno-option-ignored -Wsign-compare -Wno-extra-semi-stmt -Wno-unused-template -Wno-missing-field-initializers -Wno-deprecated-declarations -Wall -Wextra -Wcomment -Wendif-labels -Wformat -Winit-self -Wreturn-type -Wsequence-point -Wswitch -Wtrigraphs -Wundef -Wuninitialized -Wunreachable-code -Wunused -Wno-reserved-identifier -Werror -Wno-option-ignored -Wsign-compare -Wno-extra-semi-stmt -Wno-unused-template -Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-conversion -Wno-double-promotion -Wno-exit-time-destructors -Wno-extra-semi -Wno-float-conversion -Wno-gnu-anonymous-struct -Wno-gnu-zero-variadic-macro-arguments -Wno-missing-prototypes -Wno-nested-anon-types -Wno-padded -Wno-return-std-move-in-c++11 -Wno-shorten-64-to-32 -Wno-sign-conversion -Wno-unknown-warning-option -Wno-unused-command-line-argument -Wno-weak-vtables -Wno-covered-switch-default -Wno-unsafe-buffer-usage -Wno-unused-lambda-capture -Wno-bit-int-extension -Wno-pass-failed -Wno-switch-default -Werror -Weverything -Wno-undefined-func-template -DCK_TILE_FMHA_FWD_FAST_EXP2=1 -fgpu-flush-denormals-to-zero -Wno-float-equal -pthread -x hip --offload-arch=gfx90a -MD -MT example/ck_tile/01_fmha/CMakeFiles/tile_example_fmha_fwd.dir/fmha_fwd.cpp.o -MF CMakeFiles/tile_example_fmha_fwd.dir/fmha_fwd.cpp.o.d -o CMakeFiles/tile_example_fmha_fwd.dir/fmha_fwd.cpp.o -c /root/flash-attention/composable_kernel-develop/example/ck_tile/01_fmha/fmha_fwd.cpp
In file included from /root/flash-attention/composable_kernel-develop/example/ck_tile/01_fmha/fmha_fwd.cpp:4:
In file included from /root/flash-attention/composable_kernel-develop/example/ck_tile/01_fmha/fmha_fwd.hpp:6:
In file included from /root/flash-attention/composable_kernel-develop/include/ck_tile/core.hpp:36:
In file included from /root/flash-attention/composable_kernel-develop/include/ck_tile/core/tensor/shuffle_tile.hpp:18:
/root/flash-attention/composable_kernel-develop/include/ck_tile/core/utility/transpose_vectors.hpp:120:13: error: static assertion failed: not implemented
            static_assert(false, "not implemented");
            ^             ~~~~~
1 error generated when compiling for gfx90a.
make[3]: *** [example/ck_tile/01_fmha/CMakeFiles/tile_example_fmha_fwd.dir/build.make:1865: example/ck_tile/01_fmha/CMakeFiles/tile_example_fmha_fwd.dir/fmha_fwd.cpp.o] Error 1
make[3]: Leaving directory '/root/flash-attention/composable_kernel-develop/build'
make[2]: *** [CMakeFiles/Makefile2:1104: example/ck_tile/01_fmha/CMakeFiles/tile_example_fmha_fwd.dir/all] Error 2
make[2]: Leaving directory '/root/flash-attention/composable_kernel-develop/build'
make[1]: *** [CMakeFiles/Makefile2:1111: example/ck_tile/01_fmha/CMakeFiles/tile_example_fmha_fwd.dir/rule] Error 2
make[1]: Leaving directory '/root/flash-attention/composable_kernel-develop/build'
make: *** [Makefile:670: tile_example_fmha_fwd] Error 2
```
The dtypes is defined as:
```
DTYPE_MAP = {
    "fp16": "ck_tile::fp16_t",
    "bf16": "ck_tile::bf16_t",
    "fp8" : "ck_tile::fp8_t"
}
```
sizeof(dtype) will be 2 or 1, Why does the program go to this branch?

**Comment by carlushuang** [comment]
@flyingdown can you elaborate more on what is your method to reproduce this issue? We seems never meet this issue before, neither on our CI.

**Comment by JRazek** [comment]
@carlushuang shouldn't the static_assert in transpose_vectors.hpp:120 be template dependent? It seems like the code is ill formed and regardless of a chosen branch it should not compile.

ie sth like
```cpp
template <typename T>
struct dependent_false : std::false_type {};

template <typename T>
int mre() {
  if constexpr (sizeof(T) == 1) {
    return 1;
  } else if constexpr (sizeof(T) == 2) {
    return 2;
  } else {
    static_assert(dependent_false<T>::value, "unimplemented");
  }
}
```

**Comment by carlushuang** [comment]
```
template <typename S_, index_t NX, index_t NY>
struct transpose_vectors
{
    using S = remove_cvref_t<S_>;
    CK_TILE_DEVICE void operator()()
    {
        if constexpr(sizeof(S) == 2) {  ... }
        else if constexpr(sizeof(S) == 1) { ... }
        else { static_assert(false), } 
    }
};
```
@JRazek `S` is template dependent right

**Comment by JRazek** [comment]
> ```
> template <typename S_, index_t NX, index_t NY>
> struct transpose_vectors
> {
>     using S = remove_cvref_t<S_>;
>     CK_TILE_DEVICE void operator()()
>     {
>         if constexpr(sizeof(S) == 2) {  ... }
>         else if constexpr(sizeof(S) == 1) { ... }
>         else { static_assert(false), } 
>     }
> };
> ```
> 
> @JRazek `S` is template dependent right

constexpr if itself must be well formed for any possible branch. Proposed code on the other hand wont even instantiate the template (dependent_false) unless `else` branch is chosen.

**Comment by carlushuang** [comment]
@JRazek I'm not sure why you think this `constexpr if` statement is ill-formed, maybe I didn't understand your point.
![image](https://github.com/ROCm/composable_kernel/assets/8322173/5710d509-a48b-429b-8b86-95d2d4329908)

**Comment by JRazek** [comment]
@carlushuang

Even if it does not evaluate sizeof(T) == 1 or 2, the compiler will see a branch with static assert as a possible code branch. It will detect static_assert(false) as an ill-formed code even if it will never take this branch. Kind of equivalent to typing random characters and seeing that non valid syntax won't compile event if the branch won't be reached.

if constexpr does not work as `#ifdef` macro, the code still must be well formed.

`static_assert(false)` is always ill-formed, (until C++20 or 23 I believe).

**Comment by flyingdown** [comment]
@carlushuang ok,Use the following command to compile and will cause the above error:
```
mkdir build && cd build
sh ../script/cmake-ck-dev.sh  ../ gfx90a
make tile_example_fmha_fwd -j
```
I checked the code and found that the type of S does not depend on DTYPE_MAP, but is determined by the second parameter of the shuffle_tile function, so I am not sure what the size of sizeof(S) is, but it is definitely not 1 or 2. Regarding transpose_vectors, the implementation in the ck_tile branch is indeed different from the implementation in develop.

**Comment by poyenc** [comment]
@flyingdown by given commands, I cannot reproduce this issue in ROCm 6.0 nor 6.1 containers. could you provide your environment info?

**Comment by flyingdown** [comment]
@poyenc The image I use is rocm/pytorch:rocm5.6_ubuntu20.04_py3.8_pytorch_1.13.1. Is there any rocm version limit for ck?


> @carlushuang
> 
> Even if it does not evaluate sizeof(T) == 1 or 2, the compiler will see a branch with static assert as a possible code branch. It will detect static_assert(false) as an ill-formed code even if it will never take this branch. Kind of equivalent to typing random characters and seeing that non valid syntax won't compile event if the branch won't be reached.
> 
> if constexpr does not work as `#ifdef` macro, the code still must be well formed.
> 
> `static_assert(false)` is always ill-formed, (until C++20 or 23 I believe).

This statement may be correct, I tried to modify the code to the following, but the compilation still reported the same error.
```
#include "fmha_fwd.hpp"

float fmha_fwd(fmha_fwd_traits t, fmha_fwd_args a, const ck_tile::stream_config& s){
    float r = -1;

    return r;
}
```
By the way, I'm using C++17

**Comment by carlushuang** [comment]
> @poyenc The image I use is rocm/pytorch:rocm5.6_ubuntu20.04_py3.8_pytorch_1.13.1. Is there any rocm version limit for ck?
> 
> > @carlushuang
> > Even if it does not evaluate sizeof(T) == 1 or 2, the compiler will see a branch with static assert as a possible code branch. It will detect static_assert(false) as an ill-formed code even if it will never take this branch. Kind of equivalent to typing random characters and seeing that non valid syntax won't compile event if the branch won't be reached.
> > if constexpr does not work as `#ifdef` macro, the code still must be well formed.
> > `static_assert(false)` is always ill-formed, (until C++20 or 23 I believe).
> 
> This statement may be correct, I tried to modify the code to the following, but the compilation still reported the same error.
> 
> ```
> #include "fmha_fwd.hpp"
> 
> float fmha_fwd(fmha_fwd_traits t, fmha_fwd_args a, const ck_tile::stream_config& s){
>     float r = -1;
> 
>     return r;
> }
> ```
> 
> By the way, I'm using C++17

can you use rocm 6.0+ to build ck_tile ? Rocm 5.6 is quite old, will check this internally, but if this is something we didn't identified, may still suggest you to use rocm 6.0+

**Comment by poyenc** [comment]
@flyingdown Though the oldest ROCm version which can successfully compile ck_tile is **5.7**. It's recommended that to use ROCm 6.0+.

**Comment by flyingdown** [comment]
@poyenc @carlushuang It was compiled successfully and worked well under rocm 5.7 and 6.0 versions
