### ISSUE TITLE
Compile error in cpp_extension

### ISSUE THREAD

**Issue by rocking5566** [ROCm/composable_kernel#1294]
### Problem Description
This issue happen in cpp_extension. I use pytorch's cpp_extension to compile the CK instead of regular cmake.

When we cast from __half to _Float16 if to compile the ck
Error message is as follow

`
In file included from /work/flash-attention/csrc/composable_kernel/include/ck_tile/core/utility/random.hpp:7:
/work/flash-attention/csrc/composable_kernel/include/ck_tile/core/numeric/half.hpp:132:12: error: no viable conversion from returned value of type '__half' to function return type 'fp16_hip_t' (aka '_Float16')
    return __float2half(x);
           ^~~~~~~~~~~~~~~
/opt/rocm-6.0.0/include/hip/amd_detail/amd_hip_fp16.h:235:13: note: candidate function
            operator __half_raw() const { return __half_raw{data}; }
            ^
/opt/rocm-6.0.0/include/hip/amd_detail/amd_hip_fp16.h:237:13: note: candidate function
            operator __half_raw() const volatile
            ^
`

### Operating System

Ubuntu

### CPU

Intel(R) Xeon(R) Platinum 8480C

### GPU

AMD Instinct MI300X

### ROCm Version

ROCm 6.0.0

### ROCm Component

Composable Kernel

### Additional Information

Solution is as follow 
https://github.com/ROCm/composable_kernel/pull/1292

**Comment by ppanchad-amd** [comment]
@rocking5566 Is this fixed in the latest ROCm 6.2? If so, please close the ticket. Thanks!
