### ISSUE TITLE
@bghimireamd [Informative]

### ISSUE THREAD

**Issue by junliume** [ROCm/composable_kernel#1298]
@bghimireamd [Informative]

> Had to rename [MIOpen's #define ENV ](https://github.com/ROCm/MIOpen/blob/develop/src/include/miopen/env.hpp#L156) to [#define MIOPEN_ENV](https://github.com/ROCm/MIOpen/blob/426d0a17627e7d6fba555a27be8ffe612c25c97e/src/include/miopen/env.hpp#L156) because it was having name collision with recent introduction of CK's macro with same name [#define ENV](https://github.com/ROCm/composable_kernel/blob/aab4439f0f5e8c2c94c440aa103cecd1b74e3133/include/ck/utility/env.hpp#L127)

Thanks for fixing the problem.

We do not export macro as a part of our public API and therefore it is OK to define whatever we want.

If CK exports its own macro (`ENV`) in its public API, then it is CK who must take care about possible collisions with their users, for example by adding and unique prefix (like `CK_` or `COMPOSABLE_KERNELS_`). Or, better, they should avoid exporting macros in their API.

I'll take care about this.

_Originally posted by @atamazov in https://github.com/ROCm/MIOpen/issues/2961#issuecomment-2117552920_

**Comment by junliume** [comment]
Should be fixed via #1296

**Comment by illsilin** [comment]
This had been resolved by switching to CK_ENV definitions.
