### ISSUE TITLE
build examples got lld errors

### ISSUE THREAD

**Issue by ZJLi2013** [ROCm/composable_kernel#1402]
### Problem Description

base image: rocm/composable_kernel:ck_ub20.04_rocm6.1_amd-staging

```yml
[ 78%] Built target device_gemm_splitk_instance
ld.lld: error: ../../library/src/tensor_operation_instance/gpu/gemm_universal/CMakeFiles/device_gemm_universal                             _instance.dir/device_gemm_xdl_universal_f16_f16_f16/device_gemm_xdl_universal_f16_f16_f16_mk_kn_mn_comp_defaul                                          t_instance.cpp.o:(.rodata._ZN2ck16tensor_operation6device27getGemmSpecializationStringB5cxx11ERKNS1_18GemmSpec                                          ializationE+0x0): relocation R_X86_64_PC32 out of range: 2732287896 is not in [-2147483648, 2147483647]; refer                                          ences section '.text._ZN2ck16tensor_operation6device27getGemmSpecializationStringB5cxx11ERKNS1_18GemmSpecializ                                          ationE'
>>> referenced by device_gemm_xdl_universal_f16_f16_f16_mk_kn_mn_comp_default_instance.cpp

``` 

### Operating System

ubuntu 20.04

### CPU

Ryzen 

### GPU

AMD Instinct MI210

### ROCm Version

ROCm 6.0.0

### Steps to Reproduce

```sh
cmake  -D CMAKE_PREFIX_PATH=/opt/rocm  -D CMAKE_CXX_COMPILER=/opt/rocm/bin/hipcc  -D CMAKE_BUILD_TYPE=Debug  -D BUILD_DEV=ON  -D GPU_TARGETS="gfx90a" ..

# inside the container, run 
make -j examples tests
```

### Additional Information

not sure, is this related to https://github.com/ROCm/composable_kernel/issues/789#issuecomment-1653777830  , where mentioned don't build examples, and ckProfiler ?

Thanks

**Comment by illsilin** [comment]
Hmm, not sure what went wrong here. All the commands look OK.
Several possibilities:
if you ran a different cmake command previously with different options, then ran a new cmake command and then "make" without cleaning up the build folder, the build may get corrupted;
when you run "make -j", your build tries to use all the CPU cores. in case you have a CPU with many cores but a limited amout of RAM (e.g. 128 cores + 64Gb of RAM), your build may run out of memory and crash. In that case try to reduce the number of build threads.

**Comment by ZJLi2013** [comment]
rebuild again, no error now. thanks anyway
