### ISSUE TITLE
[Issue]: c++ array access assertion

### ISSUE THREAD

**Issue by trixirt** [ROCm/composable_kernel#1405]
### Problem Description

Packaging CK on Fedora uses [-Wp,-D_GLIBCXX_ASSERTIONS ](https://github.com/ROCm/composable_kernel/pull/1404)

There are several failures similar to
In file included from /home/trix/work/rocm/composable_kernel/include/ck/ck.hpp:10:                                                                                                             
In file included from /usr/include/hip/hip_runtime.h:62:                                                                                                                                       
In file included from /usr/include/hip/amd_detail/amd_hip_runtime.h:114:                                                                                                                       
In file included from /usr/include/hip/hip_runtime_api.h:568:                                                                                                                                  
In file included from /usr/include/hip/texture_types.h:47:                                                                                                                                     
In file included from /usr/include/hip/channel_descriptor.h:32:                                                                                                                                
In file included from /usr/include/hip/amd_detail/amd_channel_descriptor.h:29:                                                                                                                 
In file included from /usr/include/hip/amd_detail/amd_hip_vector_types.h:49:                                                                                                                   
/usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/array:208:2: error: reference to __host__ function '__glibcxx_assert_fail' in __host__ __device__ function                      
  208 |         __glibcxx_requires_subscript(__n);                                                                                                                                             
      |         ^                                                                                                                                                                              
/usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/debug/assertions.h:44:3: note: expanded from macro '__glibcxx_requires_subscript'                                               
   44 |   __glibcxx_assert(_N < this->size())                                                                                                                                                  
      |   ^                                                                                                                                                                                    
/usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/x86_64-redhat-linux/bits/c++config.h:2438:7: note: expanded from macro '__glibcxx_assert'                                       
 2438 |       _GLIBCXX_ASSERT_FAIL(cond);                                       \                                                                                                              
      |       ^                                                                                                                                                                                
/usr/lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/x86_64-redhat-linux/bits/c++config.h:2427:8: note: expanded from macro '_GLIBCXX_ASSERT_FAIL'                                   
 2427 |   std::__glibcxx_assert_fail(__FILE__, __LINE__, __PRETTY_FUNCTION__,   \                                                                                                              
      |        ^                                                                                                                                                                               
/home/trix/work/rocm/composable_kernel/include/ck/tensor_operation/gpu/device/impl/device_batched_contraction_multiple_d_xdl_cshuffle.hpp:526:17: note: called by 'operator()<ck::integral_con\
stant<int, 0>>'                                                                                                                                                                                
  526 |                 ds_offset[i] = static_cast<long_index_t>(g_idx) *                                                                                                                      
      |                 ^                                                                                                                                                                      
/home/trix/work/rocm/composable_kernel/include/ck/utility/functional2.hpp:22:18: note: called by 'operator()<(lambda at /home/trix/work/rocm/composable_kernel/include/ck/tensor_operation/gpu\
/device/impl/device_batched_contraction_multiple_d_xdl_cshuffle.hpp:525:44)>'                                                                                                                  
   22 |         swallow{(f(Number<Is>{}), 0)...};                                                                                                                                              
      |                  ^                                                                                                                                                                     
/home/trix/work/rocm/composable_kernel/include/ck/utility/functional2.hpp:44:9: note: called by 'operator()<(lambda at /home/trix/work/rocm/composable_kernel/include/ck/tensor_operation/gpu/\
device/impl/device_batched_contraction_multiple_d_xdl_cshuffle.hpp:525:44)>'                                                                                                                   
   44 |         detail::static_for_impl<typename arithmetic_sequence_gen<NBegin, NEnd, Increment>::type>{}(                                                                                    
      |         ^                                                                                                                                                                              
/home/trix/work/rocm/composable_kernel/include/ck/tensor_operation/gpu/device/impl/device_batched_contraction_multiple_d_xdl_cshuffle.hpp:525:13: note: called by 'GetDsPtrOffset'             
  525 |             static_for<0, NumDTensor, 1>{}([&](auto i) {                                                                                                                               
      |             ^                                               

There is something off with DS arrays' access.
This 
[shadow of NumDTensor
](https://github.com/ROCm/composable_kernel/blob/develop/include/ck/tensor_operation/gpu/device/impl/device_batched_contraction_multiple_d_xdl_cshuffle.hpp#L78) looks wrong

### Operating System

Fedora Rawhide

### CPU

x86_64

### GPU

AMD Instinct MI300X

### ROCm Version

ROCm 6.0.0

### Steps to Reproduce

build with cmake option -DUSE_GLIBCXX_ASSERTIONS=ON

**Comment by ppanchad-amd** [comment]
@trixirt Internal ticket has been created to investigate this issue. Thanks!

**Comment by tcgu-amd** [comment]
@trixirt The error message here
```
reference to host function '__glibcxx_assert_fail' in host device function
208 | __glibcxx_requires_subscript(__n);
| ^
```
seems to report that host only function `__glibcxx_assert_fail` is being referenced from  within the __host__ __device__ context [on line 525 here](https://github.com/ROCm/composable_kernel/blob/develop/include/ck/tensor_operation/gpu/device/impl/device_batched_contraction_multiple_d_xdl_cshuffle.hpp#L525), which is not allowed. 

This suggests that -DUSE_GLIBCXX_ASSERTIONS=ON is not compatible with the current build setup unfortunately. Please try disabling this option and let us know if the problem persists.

Thanks! :D

**Comment by trixirt** [comment]
For packaging on Fedora -DUSE_GLIBCXX_ASSERTIONS is a requirement, disabling likely will cause the package to be rejected from Fedora (and later RHEL)  Is there some change that could to the problem area and to document that this is a false positive ?

**Comment by tcgu-amd** [comment]
> For packaging on Fedora -DUSE_GLIBCXX_ASSERTIONS is a requirement, disabling likely will cause the package to be rejected from Fedora (and later RHEL) Is there some change that could to the problem area and to document that this is a false positive ?

@trixirt A potential option is to conditionally disable glibcxx_assertions in problematic source files that involve device-side compilations. Maybe try adding
```
#ifdef __HIP_DEVICE_COMPILE__
#undef _GLIBCXX_ASSERTIONS
#endif
```
to the beginning of the problematic source files?

**Comment by trixirt** [comment]
That sounds reasonable.  would it be appropriate if i added something like ?
// This is gpu device code, c++ cpu asserts are not expect to work here

**Comment by tcgu-amd** [comment]
> That sounds reasonable. would it be appropriate if i added something like ? // This is gpu device code, c++ cpu asserts are not expect to work here

@trixirt Yeah I think that would be a valid explanation. Please let us know if this works. Thanks!

**Comment by tcgu-amd** [comment]
Closing the issue for now since this seems to be resolved. Thanks!
