### ISSUE TITLE
[Issue]: Explicit specialization cannot have a storage class

### ISSUE THREAD

**Issue by anjenner** [ROCm/composable_kernel#1418]
### Problem Description

A recent clang change https://github.com/llvm/llvm-project/pull/93873 revealed an issue in develop branch of composable_kernel:

In file included from composable_kernel/library/src/tensor_operation_instance/gpu/grouped_conv3d_fwd_bilinear/xdl/device_grouped_conv3d_fwd_xdl_bilinear_ndhwgc_gkzyxc_ndhwgk_f16_instance.cpp:4:
In file included from composable_kernel/library/include/ck/library/tensor_operation_instance/gpu/grouped_conv_fwd/device_grouped_conv_fwd_xdl_bilinear_instance.hpp:6:
In file included from composable_kernel/include/ck/tensor_operation/gpu/device/impl/device_grouped_conv_fwd_multiple_abd_xdl_cshuffle.hpp:21:
In file included from composable_kernel/include/ck/tensor_operation/gpu/grid/gridwise_gemm_multiple_d_xdl_cshuffle.hpp:12:
In file included from composable_kernel/include/ck/tensor_operation/gpu/block/blockwise_gemm_xdlops.hpp:9:
composable_kernel/include/ck/tensor_operation/gpu/warp/xdlops_gemm.hpp:654:5: error: explicit specialization cannot have a storage class [-Werror,-Wexplicit-specialization-storage-class]
  654 |     static constexpr auto GetMfma<double, 16, 16>()
      |     ^~~~~~

and many other instances. Presumably the correct fix is just to remove "static" from all these places.

### Operating System

n/a

### CPU

n/a

### GPU

AMD Instinct MI100

### ROCm Version

ROCm 6.0.0

### ROCm Component

Composable Kernel

**Comment by ppanchad-amd** [comment]
@anjenner Internal ticket has been created to fix this issue. Thanks!

**Comment by junliume** [comment]
Static method in a template is not a good idea, but it should not be blocking/lethal either. If this is blocking your build, please consider using warning suppression first and we will fix it later.

**Comment by timchenggu123** [comment]
Assuming the issue is closed since there appear to be no more follow up. Please feel free to comment/reopen if further problems arise. Thanks!

**Comment by illsilin** [comment]
I fixed this issue: https://github.com/ROCm/composable_kernel/pull/1533
