### ISSUE TITLE
Naming for Reduction Operation

### ISSUE THREAD

**Issue by asroy** [ROCm/composable_kernel#144]
_Originally posted by @j4yan in https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/128#discussion_r832741425_

# IdentityValue
This value is a mathematical property of reduction type, and should be deterministic and not specified by user of reduction

https://docs.oracle.com/javase/tutorial/collections/streams/reduction.html

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/22615726/159810675-28ef87b2-4cdb-4cb3-a7ae-e89103e78a88.png">

# InitialValue
This value could be specified at runtime, it could be used in multi-stage reduction to hold the accumulated value of previous reduction

# Suggested implementation
```
struct BaseReductionType {};

template<typename T>
struct ReduceSum : public BaseReductionType
{
    static constexpr T kIdentityValue = T{0}; // not modifiable
    
   constexpr T Reduce(T& acc, const T& v)
   {
       acc += v;
   }
};

template<typename ReduceType,
                  typename T>
struct ReductionOperation
{
    T initialValue_ = ReduceType::kIdentityValue; // modifiable
    
   constexpr T SetInitialValue(T& v)
   {
       initialValue_ = v;
   }

   constexpr T InitializeAcc(T& acc)
   {
       acc = initialValue_;
   }

   constexpr T Reduce(T& acc, const T& v)
   {
       ReduceType::Reduce(acc, v);
   }
};
```

# Pointwise operation for reduction should be unified with normal pointwise operation
https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/91d8b7d67ae9dbf8a6e691ea3e17c0b9705c6ba7/include/ck/tensor_operation/gpu/element/element_wise_operation.hpp#L146-L330

A strange use case of ```UnaryIdentic```

**Comment by qianfengz** [comment]
The two Reduction Operations is not added by my generic reduction codes.  It is used by Chao or JianFeng's  fusion kernels.  Generic Reduction defined Reduction Operator is in file [reduction_operator](https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/develop/include/ck/utility/reduction_operator.hpp)

Later,   I will provide P.R to help improving the fusion codes which uses Reduction,  the two Reduction Operations will be removed step by step.

**Comment by qianfengz** [comment]
ReduceSum and ReduceSquareSum were removed in [PR.211](https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/211/commits/cf720e8ce882695548b667be7aa879b31f565c60)

**Comment by qianfengz** [comment]
We need discussion on how to unify the Elementwise operator used by Reduction and other part of C.K.

**Comment by qianfengz** [comment]
[P.R 274](https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/274)   is related.

**Comment by schung-amd** [comment]
Stale, can revisit in the future as part of future refactoring plans if needed.
