### ISSUE TITLE
Python minimal version requirement needs to be updated for CK FMHA Codegen

### ISSUE THREAD

**Issue by junliume** [ROCm/composable_kernel#1466]
https://github.com/ROCm/composable_kernel/blob/ab60b390f892052cee5ccbd68464caecec6981d9/CMakeLists.txt#L29

This line needs to be updated since

```
File "/long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/composable_kernel/example/ck_tile/01_fmha/codegen/ops/fmha_fwd.py", line 6, in <module>
  from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
```

This is Python version issue: dataclasses are a new feature of python 3.7 (not 3.6 as default in RHEL8.x and SLES15.x OS).

**Comment by illsilin** [comment]
I propose to upgrade to version 3.11.

**Comment by illsilin** [comment]
Apparently, requiring the minimum python version higher than 3.6 will cause the builds to fail on older operating systems, such as RHEL8 or SLES15. But I've implemented a workaround, where we can switch the python executables to the newer versions using "CK_USE_ALTERNATIVE_PYTHON" build argument and get the builds to work correctly.
