### ISSUE TITLE
Run cmake for the second time will cause policy CMP0002 another target with the same name already exists

### ISSUE THREAD

**Issue by junliume** [ROCm/composable_kernel#1510]
**the error**:
```
CMake Error at cmake/ClangTidy.cmake:149 (add_custom_target):
  add_custom_target cannot create target
  "tidy-target-device_mha_instance-fmha_fwd_d128_bf16_batch_shb_b128x128x32x128x32x128_r4x1x1_w32x32x16_qr_vr_psskddv_bias_mask_lse_dropout_cpp"
  because another target with the same name already exists.  The existing
  target is a custom target created in source directory
  "/data/driver/composable_kernel/library/src/tensor_operation_instance/gpu/mha".
  See documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  library/src/tensor_operation_instance/gpu/CMakeLists.txt:122 (clang_tidy_check)
  library/src/tensor_operation_instance/gpu/mha/CMakeLists.txt:57 (add_instance_library)

```

**Reproducible Steps:**
- Clone Composable Kernel Repo
- mkdir build;cd build
- VERBOSE=1 CXX=/opt/rocm/bin/amdclang++ cmake -DCK_USE_ALTERNATIVE_PYTHON="/opt/Python-3.8.13/bin/python3.8" -DCMAKE_PREFIX_PATH=/opt/rocm -DCMAKE_BUILD_TYPE=Release -DGPU_TARGETS="gfx942" .. 2>&1 | tee cmake.log
- Run the same command again for the second time

**Comment by junliume** [comment]
@illsilin and @bghimireamd this issue is high urgency because:
- If dev change code and try to build CK incrementally, it will meet with policy CMP0002 error
- The error is simple to reproduce even without building the code

The issue is most likely related to `library/src/tensor_operation_instance/gpu/mha/CMakeLists.txt` 
- It is adding instances from `example/ck_tile/01_fmha/generate.py` again?

**Comment by illsilin** [comment]
The mha library should be built inside the ck_tile folder, instead of copying the files elswhere and building them there, as I've been saying all along.
