### ISSUE TITLE
[Issue]: amd_wave_read_first_lane is ambiguous

### ISSUE THREAD

**Issue by RichardGe** [ROCm/composable_kernel#1551]
### Problem Description

I'm building on Windows,  with those parameters:
```
cmake .. -G "Ninja" ^
    -DCMAKE_C_COMPILER="C:\Program Files\AMD\ROCm\6.2\bin/clang.exe" ^
    -DCMAKE_CXX_COMPILER="C:\Program Files\AMD\ROCm\6.2\bin/clang++.exe" ^
    -DCMAKE_BUILD_TYPE=Release ^
    -DGPU_TARGETS="gfx1100" ^
    -DCMAKE_HIP_COMPILER="C:\Program Files\AMD\ROCm\6.2\bin/clang.exe" ^
    -DBUILD_TESTING=Off ^
    -DBUILD_DEV=Off ^
    -DCMAKE_OBJECT_PATH_MAX=300 ^
    -DINSTANCES_ONLY=ON ^
    -DROCM_DIR="<my path to rocm>\git\rocm-cmake\INSTALL\share\rocm\cmake"
```

I'm on `rocm-6.2.1`

I have a lots of errors like that:
```
error: call to 'amd_wave_read_first_lane' is ambiguous
   68 |         amd_wave_read_first_lane(compute_ptr_offset_of_batch.GetEPtrOffset(g_idx));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
H:/dev/ck/include\ck/utility/amd_wave_read_first_lane.hpp:98:28: note: candidate function
   98 | __device__ inline uint32_t amd_wave_read_first_lane(uint32_t value)
      |                            ^
H:/dev/ck/include\ck/utility/amd_wave_read_first_lane.hpp:103:27: note: candidate function
  103 | __device__ inline int32_t amd_wave_read_first_lane(int32_t value)
      |                           ^
H:/dev/ck/include\ck/utility/amd_wave_read_first_lane.hpp:108:27: note: candidate function
  108 | __device__ inline int64_t amd_wave_read_first_lane(int64_t value)
      |                           ^
	  
```

My current workaround is to cast like that, but I don't know if it's a good solution:
`amd_wave_read_first_lane(    (int64_t)   compute_ptr_offset_of_batch.GetEPtrOffset(g_idx));`

### Operating System

Windows

### CPU

AMD Ryzen Threadripper PRO 5955WX 16-Cores

### GPU

AMD Radeon Pro W7800

### ROCm Version

ROCm 6.0.0

**Comment by carlushuang** [comment]
`compute_ptr_offset_of_batch.GetEPtrOffset(g_idx)` if this function return int32/64? the ambiguous seems just the input arg looks ambiguous for the compiler guys, so maybe you can cast this to int32 or 64 explicitly (same as your workaround)

**Comment by ppanchad-amd** [comment]
Hi @RichardGe. Has your issue been resolved? Thanks!

**Comment by RichardGe** [comment]
@ppanchad-amd .
I haven't tested on newer version than 'rocm-6.2.1', so I don't know. if I have some free time in the future I'll test on newer version of rocm

**Comment by darren-amd** [comment]
Hi @RichardGe,

Created a PR here: https://github.com/ROCm/composable_kernel/pull/1631 that addresses your issue. Should be fixed once the patch is released, thanks for the report!
