### ISSUE TITLE
[Issue]: FMHA change of drop_seed_offset to std::variant is breaking builds

### ISSUE THREAD

**Issue by iratebadger** [ROCm/composable_kernel#1638]
### Problem Description

The change of drop_seed_offset from a std::pair<uint64_t, uint64_t> to a std::variant<std::pair<uint64_t, uint64_t>, std::pair<const void*, const void*>> is breaking builds in a trivial manner. This should have become 2 or more constructors one with each of the types that is then passed to a std::variant version explicitly. As it stands it requires some kind o ugly code for end users.

### Operating System

24.04

### CPU

Ryzen 7 / NA

### GPU

AMD Instinct MI100

### ROCm Version

ROCm 6.0.0

### ROCm Component

Composable Kernel

### Steps to Reproduce

Pull latest xformers or flash_attention and try to build using latest CK

### Additional Information

This is a fixable issue but it requires all end users to change their code and I think there is a fix here that could result in better outcomes.

**Comment by schung-amd** [comment]
Hi @iratebadger, slight clarification: it looks to me like prior to this change the input was an `std::tuple`, not `std::pair`, is that correct? I think a pair should be implicitly converted to the variant, but the tuple would not and I can take a look at adding back in support for that.

**Comment by poyenc** [comment]
Hi @iratebadger could you provide an example to demonstrate how you invoke the `MakeKargs()` method? For I know, passing `std::make_pair()` argument should be fine. But constructing `std::variant<>` parameter directly from list initializer is not possible now.

**Comment by schung-amd** [comment]
Backward compatibility with list initializers and tuples added by https://github.com/ROCm/composable_kernel/pull/1689 and https://github.com/ROCm/composable_kernel/pull/1681, which should resolve this issue. Feel free to comment if further related issues arise and we can reopen if necessary. Thanks for reporting this!
