### ISSUE TITLE
elementwise operation Support 1D~5D

### ISSUE THREAD

**Issue by rocking5566** [ROCm/composable_kernel#203]
We only support 2D (DeviceBinaryElementWise2D) so far.

Support more dimension for flexibility

**Comment by rocking5566** [comment]
https://ontrack-internal.amd.com/browse/LWPCK-190

**Comment by asroy** [comment]
more specifically, we should have a single device operation class that support 1D~5D tensor elementwise operation, instead of 5 device operation classes.

**Comment by ppanchad-amd** [comment]
@rocking5566 Please advise if we can go ahead and close this ticket as fixed. Thanks!

**Comment by rocking5566** [comment]
@ppanchad-amd 
As mention in the https://ontrack-internal.amd.com/browse/LWPCK-190
We can close this ticket
