### ISSUE TITLE
major code refactor

### ISSUE THREAD

**Issue by asroy** [ROCm/composable_kernel#221]
# major
- [x] Add license
- [x] use absolute path for header
- [x] fix header dependency: https://github.com/ROCmSoftwarePlatform/composable_kernel/issues/170
- [ ] Tensor operation naming: grid/block/warp/thread-level operation, conv/gemm/reduce/elementwise operation
- [x] https://github.com/ROCmSoftwarePlatform/composable_kernel/issues/198
- [ ] ~~https://github.com/ROCmSoftwarePlatform/composable_kernel/issues/169~~

# misc
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/issues/146
- [x] use is_same_v instead of is_same https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/175#discussion_r860513003
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/issues/90

**Comment by asroy** [comment]
@poyenc If you see any issue with the coding, please add them in the description above. I will fix them in a major refactor PR

**Comment by schung-amd** [comment]
Stale, can revisit in the future as part of future refactoring plans if needed.
