### ISSUE TITLE
github allow "merge" PR even CI is not finished

### ISSUE THREAD

**Issue by asroy** [ROCm/composable_kernel#227]
For some reason, if CI passed previously for a old commit, github will allow "merge" option, even new CI of new commit is not finished.

<img width="517" alt="image" src="https://user-images.githubusercontent.com/22615726/167269165-2bed9503-a96f-4cda-8094-71081c0b965a.png">

<img width="864" alt="image" src="https://user-images.githubusercontent.com/22615726/167269351-bb763471-06db-496d-b230-d3daa5f29c23.png">

**Comment by illsilin** [comment]
I think this is no longer an issue. Our CI is pretty stable now and sometimes we feel confident enough to merge PRs without waiting for CI to finish.
