### ISSUE TITLE
Disable K-pad checking during main loop

### ISSUE THREAD

**Issue by rosenrodt** [ROCm/composable_kernel#325]
GridwiseGemm implementations guarantees that there won't be out-of-range (padded) addresses along K0/K1 in the main loop. But it currently does not leverage that fact yet

@asroy once suggested adding a hook or something in the A/B tensor descriptor to disable K-pad checking during main loop, but did not rule out that there could be better ways to achieving the same effect.

**Comment by darren-amd** [comment]
Hi @rosenrodt,

Thanks for the suggestion, I was wondering if you were still looking for this enhancement? I can pass it along to the internal team to evaluate, thanks!

**Comment by darren-amd** [comment]
Going to close this ticket due to inactivity, please feel free to create another one if the issue persists, thanks!
