### ISSUE TITLE
Cosmetic issues in recent GEMM+GEMM PRs

### ISSUE THREAD

**Issue by asroy** [ROCm/composable_kernel#407]
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/395#discussion_r964097258
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/395#discussion_r964097985
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/395#discussion_r964098118
- [ ] https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/399#discussion_r964049341

**Comment by taylding-amd** [comment]
I will be closing the issue, as the concerns mentioned in the comments have already been addressed in the latest development branch.
