### ISSUE TITLE
Add group attention instances

### ISSUE THREAD

**Issue by rosenrodt** [ROCm/composable_kernel#431]
We do not have grouped att for now, @rosenrodt . @asroy Do we need instances for group bmm+softmax+gemm+permute

_Originally posted by @shaojiewang in https://github.com/ROCmSoftwarePlatform/composable_kernel/issues/425#issuecomment-1252494368_

**Comment by ppanchad-amd** [comment]
@rosenrodt Is this ticket still relevant? If not, please close the ticket. Thanks!
