### ISSUE TITLE
Tags for ROCm releases

### ISSUE THREAD

**Issue by tpkessler** [ROCm/composable_kernel#543]
Hi! I'm the maintainer of ROCm community packages for [Arch Linux](https://github.com/rocm-arch/rocm-arch). Would it be possible to add tags / releases that match ROCm and MIOpen releases?  This would greatly simplify the packaging of MIOpen. Currently, the correct commit tag needs to be extracted from `requirements.txt` in the MIOpen repo.

**Comment by geyyer** [comment]
Hi @tpkessler, thanks for pinging! We are discussing possible release strategies, but haven't decided yet... let us get back to you in early 2023.

**Comment by geyyer** [comment]
@tpkessler, @Madouura, the CK library is not yet officially shipped as a part of ROCm package. Starting with the next release ROCm v5.6 it will be a part of the package and there will be a direct match with ROCm and MIOpen versions, stay tuned!

**Comment by cgmb** [comment]
CK appears to have been overlooked during in the ROCm 5.6.0 release tagging process.

**Comment by trixirt** [comment]
Fedora says 'Me too!' MIOpen 5.6 is on our list for packages and this is a dependent package so I am looking for the tarball,  can one be tagged and cut from the release/rocm-rel-5.6 branch ?

**Comment by ckastner** [comment]
Debian would also like to ask for a tagged release, as we're packaging CK as a dependency of MIOpen.

**Comment by tpkessler** [comment]
> CK appears to have been overlooked during in the ROCm 5.6.0 release tagging process.

Same with the 5.6.1 release.

**Comment by Mystro256** [comment]
With that said, I noticed that 5.7.0 was successfully tagged
