### ISSUE TITLE
Confusion about the client examples for quantization

### ISSUE THREAD

**Issue by iq136boy** [ROCm/composable_kernel#662]
I found some confusion (typo?) in the client examples for quantization in CK.  For example, in [this example](https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/develop/client_example/09_quantization/conv2d_fwd_perchannel_quantization.cpp)
Line 61:  std::array<ck::index_t, 5> requant_scale_lengths{G, N, K, Ho, Wo};
But when allocate memory in line 72, it become:
SimpleDeviceMem requant_scale(sizeof(RequantScaleDataType)* K * Y * X * C)*;

Also, based on  my understanding, the number (size) of quantization scales should be K (or G*K) since it is perchannel quantization. Is this the case for the perchannel quantization kernel for CK?

I open this issue after talk with @zjing14.

**Comment by zjing14** [comment]
PR #672

**Comment by zjing14** [comment]
PR Merged
