### ISSUE TITLE
[CI] splitK_gemm related tests failing after #644 and ROCm 5.5 dockers

### ISSUE THREAD

**Issue by junliume** [ROCm/composable_kernel#666]
**[Symptoms]**

-  This issue is not found in current CI because CI docker uses "N-1" version of ROCm
-  This exposed an issue with current process: we need staging to expose potential problems withthe "latest and greatest" of all dependencies

Below listed five tests are failing:

 99 - example_splitK_gemm_xdl_fp32 (Subprocess aborted)
100 - example_splitK_gemm_xdl_fp16 (Subprocess aborted)
101 - example_splitK_gemm_xdl_bfp16 (Failed)
102 - example_splitK_gemm_xdl_int8 (Subprocess aborted)
143 - test_gemm_split_k (Failed)

**[reproduce steps]**
using the `rocm/miopen:debug_2063` docker
```
git clone https://github.com/ROCmSoftwarePlatform/composable_kernel
cd composable_kernel/
mkdir build && cd build
cmake -DBUILD_DEV=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=/opt/rocm/bin/hipcc -DGPU_TARGETS="gfx908;gfx90a" -DCMAKE_PREFIX_PATH=/opt/rocm ..
make -j$(nrpoc) check
```

**[Action Plans]**

- #665 is created
- Daily development happens on `develop` branch
- Every week, @zjing14 @junliume  merge `develop` branch to `staging` branch, and ask CQE to perform staging tests on `staging` branch (currently, run latest stable main branch from all components and run all unit tests)
- Only when staging has passed, we merge `staging` branch into `master` branch

- `master` branch is where we **deliver** to any internal and external customers.
- MIOpen dependency on CK should be a "tag" on `master` branch.
- In future releases, proper ROCm release branch needs to be *cut* from `master` branch, and tagged properly.

**Comment by junliume** [comment]
Issue should not be completed closed until all action items have been reviewed and implemented.

**Comment by carlushuang** [comment]
compiler issue, fired a JIRA: [SWDEV-393277](https://ontrack-internal.amd.com/browse/SWDEV-393277)

**Comment by illsilin** [comment]
We have switched to a new compiler based on this rocm5.6 build:
http://rocm-ci.amd.com/job/compute-rocm-dkms-no-npi-hipclang/11914/
With this compiler all the tests are passing, so we are going to put the split-k gemm code back in.

**Comment by illsilin** [comment]
We have put the split-k gemm kernels back. Everything is working correctly on MI100 and MI200. I will keep monitoring newer rocm5.6 release candidates to make sure the issue does not return.
