### ISSUE TITLE
3D forward group convolution kernel instances for NDHWGC layout

### ISSUE THREAD

**Issue by iq136boy** [ROCm/composable_kernel#719]
The 3D forward group convolution CK kernel instances with NDHWGC layout are not supported.

**Comment by zjing14** [comment]
https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/d821d1e54f6ce8131070a1253dfc4dd6662d3d85/library/include/ck/library/tensor_operation_instance/gpu/grouped_convolution_forward.hpp#LL263C1-L264C1 Does these instance fit your needs?
