### ISSUE TITLE
Flash Attention not correct if (some specially shaped) bias is added

### ISSUE THREAD

**Issue by cloudhan** [ROCm/composable_kernel#728]
To reproduce:

```bash
#!/bin/bash

git clone https://github.com/cloudhan/composable_kernel.git -b bug-report-flash-attn-mask 
cd composable_kernel
mkdir -p build
cd build

# Need to specify target ID, example below is for gfx908 and gfx90a
cmake \
  -DCMAKE_GENERATOR=Ninja \
  -DCMAKE_PREFIX_PATH=/opt/rocm \
  -DCMAKE_CXX_COMPILER=/opt/rocm/bin/hipcc \
  -DCMAKE_CXX_FLAGS="-O3" \
  -DCMAKE_BUILD_TYPE=Release \
  -DGPU_TARGETS="gfx90a" \
  ..

ninja example_gemm_bias_softmax_gemm_permute

#                                                    N      G0      
./bin/example_gemm_bias_softmax_gemm_permute 1 4 0 1 5 32 32 5 1 0.125
./bin/example_gemm_bias_softmax_gemm_permute 1 4 0 1 5 32 32 7 1 0.125
./bin/example_gemm_bias_softmax_gemm_permute 1 4 0 1 3 32 32 8 1 0.125
./bin/example_gemm_bias_softmax_gemm_permute 1 4 0 1 5 32 32 8 1 0.125
```

For the bias `d0_gs_ms_ns`, the shape:stride is (G0, G1, M, N):(N, 0, 0, 1) , so it can be think of as a bias of 2D G0 x N.
In the above first example, the bias is specially constructed as:
```
[[     0.      0.      0. -10000.      0.]
 [     0.      0. -10000.      0.      0.]
 [     0. -10000.      0.      0.      0.]
 [-10000.      0.      0.      0. -10000.]
 [     0.      0.      0. -10000.      0.]]
```

The obvious failure pattern is when N is an odd number and small enough (<= 5), the numerical check will fail.

**Comment by ltqin** [comment]
pls check [PR733](https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/733)

**Comment by zjing14** [comment]
#733 is merged. @cloudhan please check.

**Comment by cloudhan** [comment]
@zjing14 The fix is not a desired resort.

https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/d1838d328c2bf7119af5dddc522ccf37dba33c3f/include/ck/tensor_operation/gpu/device/impl/device_batched_gemm_softmax_gemm_permute_xdl_cshuffle.hpp#L785-L795

The dimension of `d0` is of shape [G0, G1, q_seqlen, k_seqlen], by limiting `IsSupportedArgument` only to vector loadable shape severely limit the applicability of the kernel. Instead, I think ck should fallback to scalar load in this case (and on the fringe).

Also, you should not `std::cout` here.

**Comment by zjing14** [comment]
@ltqin We need to add instances with scalar loads as fallback.

**Comment by ltqin** [comment]
@zjing14  @cloudhan 
vector load = 1 is scalar load
https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/develop/library/src/tensor_operation_instance/gpu/batched_gemm_softmax_gemm_permute/device_batched_gemm_bias_softmax_gemm_permute_xdl_cshuffle_f16_f16_f16_f16_gmk_gnk_gno_gmo_instance.cpp#L48

**Comment by cloudhan** [comment]
The fix is verified, I need to add two new instances to my lists.

@ltqin  Please remove the `std::out`

**Comment by ltqin** [comment]
@cloudhan @zjing14  remove useless comments
[PR760](https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/760)

**Comment by cloudhan** [comment]
Fix verified.
