### ISSUE TITLE
Does CK conv2d surport NCHW input?

### ISSUE THREAD

**Issue by zslovelq** [ROCm/composable_kernel#748]
Example and client_example only show NHWC demo，but I need NHWC input.
 Input ,weight and output dim-permute is  slow.
I need rewrite ck::tensor_operation::device::DeviceGroupedConvFwdDlMultipleD_NHWC_KYXC_NHWK to ck::tensor_operation::device::DeviceGroupedConvFwdDlMultipleD_NCHW_KCYX_NKHW。
But it's too difficult for me.

**Comment by bartekxk** [comment]
Hi @zslovelq. Yes, please try grouped convolution forward with group equal to 1.

**Comment by illsilin** [comment]
Sounds like this is resolved.
