### ISSUE TITLE
Need additional bias input for `DeviceBatchedGemmGemm_Xdl_CShuffle` fusion

### ISSUE THREAD

**Issue by cloudhan** [ROCm/composable_kernel#756]
For attention, FFN part can leverage this fusion pattern.
```
data -> gemm -> elementwise activation -> gemm 
```

However, `DeviceBatchedGemmGemm_Xdl_CShuffle` is lacking very critical bias input
```
data -> gemm -> add -> elementwise activation -> gemm 
                /
             bias_data
```

**Comment by zjing14** [comment]
@ltqin Could you take care of this issue?

**Comment by ltqin** [comment]
@cloudhan  you can use DeviceBatchedGemmMultipleDGemmMultipleD_Xdl_CShuffle instead of DeviceBatchedGemmGemm_Xdl_CShuffle

**Comment by cloudhan** [comment]
@ltqin I am wondering if is there any performance advantage for `DeviceBatchedGemmGemm_Xdl_CShuffle` over `DeviceBatchedGemmMultipleDGemmMultipleD_Xdl_CShuffle` when we don't have bias?

**Comment by ltqin** [comment]
> @ltqin I am wondering if is there any performance advantage for `DeviceBatchedGemmGemm_Xdl_CShuffle` over `DeviceBatchedGemmMultipleDGemmMultipleD_Xdl_CShuffle` when we don't have bias?

should have same performance if we don't have bias
