### ISSUE TITLE
Use DPP8 Gemm for Navi21

### ISSUE THREAD

**Issue by zjing14** [ROCm/composable_kernel#772]
- Use DPP8 Gemm utilizes implemented by @geyyer in (https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/657/) to finish a fp16 Gemm example
- @bwroblew

**Comment by ppanchad-amd** [comment]
@zjing14 Is this ticket still relevant? If not, please close the ticket. Thanks!

**Comment by bwroblew** [comment]
I implemented the requested feature in the following PRs:
- https://github.com/ROCm/composable_kernel/pull/826
- https://github.com/ROCm/composable_kernel/pull/863
- https://github.com/ROCm/composable_kernel/pull/892
- https://github.com/ROCm/composable_kernel/pull/896

As far as I know, there are no further requirements regarding the DPP8 kernels for Navi21. @bartekxk, could you confirm that, please?

**Comment by bartekxk** [comment]
I think mentioned pull requests are sufficient for above request. I will close the ticket.
