### ISSUE TITLE
Aborted when running example_put_element_fp16

### ISSUE THREAD

**Issue by evshiron** [ROCm/composable_kernel#780]
Greetings.

I was building CK locally in a container built from your Dockerfile, but when running `example_put_element_fp16` it aborted:

```
root@container:/mnt/ck/build# ./bin/example_put_element_fp16 
example_put_element_fp16: /mnt/ck/library/include/ck/library/utility/host_tensor.hpp:129: std::size_t HostTensorDescriptor::GetOffsetFromMultiIndex(Is...) const [Is = <int>]: Assertion `sizeof...(Is) == this->GetNumOfDimension()' failed.
Aborted (core dumped)
```

If I am correct, we declare `indices` as a 2D tensor, but access it with only one index [here](https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/develop/example/50_put_element/put_element_fp16.cpp#L43).

The fix is easy, just add the missing index. But I am curious how the test passes in CI as indicated from GitHub?

**Comment by zjing14** [comment]
@rocking5566  Could you take a look this issue?

**Comment by rocking5566** [comment]
I declare the tensor tensor as 1D tensor in this PR https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/812
Just wait for merge
