### ISSUE TITLE
[Critical] ckProfiler link failure with relocation out of range error

### ISSUE THREAD

**Issue by junliume** [ROCm/composable_kernel#789]
**Updated 07/18**: 

**Symptoms**:
`ckProfiler` is too large and triggered Relocation Overflow (`relocation R_X86_64_PC32 out of range`) e.g.
```
ld.lld: error: CMakeFiles/ckProfiler.dir/profile_gemm.cpp.o:(.rodata._ZN6TensorIfE19GenerateTensorValueI17GeneratorTensor_2IfEEEvT_m+0x0): 
relocation R_X86_64_PC32 out of range: 2829150605 is not in [-2147483648, 2147483647]; references section '.text._ZN6TensorIfE19GenerateTensorValueI17GeneratorTensor_2IfEEEvT_m'
>>> referenced by profile_gemm.cpp
```

**Steps to Reproduce**:
```
export CK_COMMIT=18435a8e5c95b79ece77fd07fc22c6462a20dafb && mkdir /tmp/ck && \
wget -O ck.tar.gz https://www.github.com/rocmsoftwareplatform/composable_kernel/archive/${CK_COMMIT}.tar.gz -O /tmp/ck.tar.gz && \
tar zxvf /tmp/ck.tar.gz -C /tmp/ && mkdir /tmp/composable_kernel-${CK_COMMIT}/build && \
cd /tmp/composable_kernel-${CK_COMMIT}/build && \
CXX=/opt/rocm/llvm/bin/clang++ cmake -DCMAKE_CXX_COMPILER_LAUNCHER="${COMPILER_LAUNCHER}" \
-DCMAKE_PREFIX_PATH=/opt/rocm -DDTYPES="fp16;fp32;bf16" -DCMAKE_BUILD_TYPE=Release \
-DGPU_TARGETS="gfx900;gfx906;gfx908;gfx90a;gfx940;gfx941;gfx942;gfx1030;gfx1100;gfx1101" .. && \
time make -j$(nproc)  2>&1 | tee build.log
```
after observing the above failure:
```
cd /tmp/composable_kernel-ba16e36142078adc6ba599328831b34d0e659c9e/build/profiler/src && \
/opt/conda/envs/py_3.8/bin/cmake -E cmake_link_script CMakeFiles/ckProfiler.dir/link.txt --verbose=1
```
then we get the link command
```
/opt/rocm/llvm/bin/clang++ -O3 -DNDEBUG @CMakeFiles/ckProfiler.dir/objects1.rsp \
-o ../../bin/ckProfiler  -Wl,-rpath,/opt/rocm/lib: ../../lib/libutility.a -pthread /opt/rocm/lib/libamdhip64.so.5.7.50700 \
--hip-link --offload-arch=gfx900 --offload-arch=gfx906 --offload-arch=gfx908 --offload-arch=gfx940 \
--offload-arch=gfx941 --offload-arch=gfx942 --offload-arch=gfx90a --offload-arch=gfx1030 --offload-arch=gfx1100 \
--offload-arch=gfx1101 --offload-arch=gfx1102 \
/opt/rocm-5.7.0-12468/llvm/lib/clang/17.0.0/lib/linux/libclang_rt.builtins-x86_64.a
```

**Investigations**:
- The file sizes of `@CMakeFiles/ckProfiler.dir/objects1.rsp`
The total file size to be linked together exceeed 2G (3.3 GB in this case)
[ckProfiler_link.log](https://github.com/ROCmSoftwarePlatform/composable_kernel/files/12089682/ckProfiler_link.log)
- Varying the link command above does not work
    - `-gsplit-dwarf=split -O3 -fPIC ` does not work on the kernel code
    -  Reducing the number of `--offload-arch` in the link command does not work.
    -  `-mcmodel=medium` does not work either

**Comment by illsilin** [comment]
I have observed similar linker errors while experimenting with compiler flags trying to build a DEBUG build for the code coverage.

Please try replacing the "-DCMAKE_CXX_FLAGS=" -O3 "" with "-DCMAKE_BUILD_TYPE=Release" in the cmake command line and the error should go away.

**Comment by junliume** [comment]
We need to fix `DEBUG` build nevertheless :)

**Comment by junliume** [comment]
Track this issue:
> -DGPU_TARGETS="gfx900;gfx906;gfx908;gfx90a;gfx940;gfx941;gfx942;gfx1030;gfx1100;gfx1101;gfx1102"

This list is just too long and eventually we will get `ckProfiler` out of binary size bound issue.

**Comment by illsilin** [comment]
I think we now understand the problem. The solution is to build just library and instances for all gpu targets skipping the tests, examples, and ckProfiler. When we get to build the ckProfiler, we shall build it for each architerture, e.g. gfx9, gfx10, gfx11, separately.
