### ISSUE TITLE
Support Optional GPU Targets by checking compiler support

### ISSUE THREAD

**Issue by junliume** [ROCm/composable_kernel#793]
https://github.com/ROCmSoftwarePlatform/MIOpen/issues/2256

I think this issue would be better solved by CK team.

**Comment by illsilin** [comment]
We've implemented a slightly different way to do this: if GPU_TARGETS are set on the cmake command line, we will try to build for those targets. If GPU_TARGETS are not set, we will build for all targets supported by the compiler.
