### ISSUE TITLE
Forbid  type_convert<bhalf_t, int32_t> and type_convert<int32_t, bhalf_t> 

### ISSUE THREAD

**Issue by qianfengz** [ROCm/composable_kernel#801]
In CK `bhalf_t` is defined by `using bhalf_t = unsigned short`.  Also `type_convert<bhalf_t, float>` as well as `type_convert<float, bhalf_t>` is used for correctly understanding the values of `bhalf_t` before writing/reading them to/from device memory.  

If `type_convert<bhalf_t, int32_t>` and `type_convert<int32_t, bhalf_t>` are defined to convert directly between `bhalf_t` and `int32_t`,  we will not be able to do normal conversion between `unsigned short` and `int32_t`  inside `ThreadwiseTensorTransfer_xxx` which implicitly depends on `type_convert`.  

Also I think we have no reason to use `type_convert` between `bhalf_t` and 'int32_t` since in CK `bhalf_t` values are completely converted to `float` in registers when loaded from device memory. 

So I suggest to remove those codes in `include/ck/type_convert.hpp` for `bhalf_t` and `int32_t` conversion.

**Comment by qianfengz** [comment]
@zjing14 @asroy 
Please take a look.   Don't know when `type_convert<bhalf_t, int32_t>`,  `type_convert<bhalf_t, int32_t>` are added.   It seems currently there is no codes using them.   Since when have them removed, the "make -j 64 check" can still pass. 

Since CK `flashAttention` is using`type_convert<unsigned short, int32_t>` for transferring the random numbers generated from kernel to host during verification testing,   we need to remove the above `type_convert` to make `flashAttention` testing examples passed when merged with develop.

**Comment by zjing14** [comment]
@geyyer Please take a look at the issue.

**Comment by geyyer** [comment]
@qianfengz, indeed, currently we don't use the bf16<->int32 conversions, the PR https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/802 removes this functionality, we can do it harmlessly.

BTW, could you share some info on bhalf_t conversion to float when loaded from device memory?

**Comment by qianfengz** [comment]
> @qianfengz, indeed, currently we don't use the bf16<->int32 conversions, the PR #802 removes this functionality, we can do it harmlessly.
> 
> BTW, could you share some info on bhalf_t conversion to float when loaded from device memory?

`bhalf_t` and `float` conversion is implemented by Chao.   The point is that each value of 16-bit should be understood as bf16 when converted to a numerically equal value of float,  so we just can not use `static_cast<bhalf_t>(float xx)` since bhalf_t is `unsigned int`.  

These conversions are done implicitly when reading/writing to from device memory by calling `ThreadwiseTensorTransfer_xxx` interfaces, which has `srcDataType` and `dstDataType` as template parameters.  `type_convert` is called implicitly inside `ThreadwiseTensorTransfer_xx` to convert values of `srcDataType` to `dstDataType` after reading from or before writing to device memory

**Comment by geyyer** [comment]
PR https://github.com/ROCmSoftwarePlatform/composable_kernel/pull/802 merged.
