### ISSUE TITLE
[ROCm 5.7] HIP kernels may launch with non-uniform block size for backward compatibility

### ISSUE THREAD

**Issue by junliume** [ROCm/composable_kernel#837]
Similar to https://github.com/ROCmSoftwarePlatform/MIOpen/pull/2307

We need to add the compiler option `-fno-offload-uniform-block` when building CK kernels using compiler which comes with ROCm 5.7.

**Comment by atamazov** [comment]
@junliume Is it so that the issue happens with CK kernels?

@illsilin Please look at https://github.com/ROCmSoftwarePlatform/MIOpen/pull/2307#issuecomment-1671699031.

**Comment by junliume** [comment]
@illsilin could you check or confirm if CK kernels have ever used non-uniform block size? If it has always been assuming uniform block size then we do not need this workaround and potential perf issues come with it.

**Comment by illsilin** [comment]
FYI, running CK build and performance tests with ROCM5.7 RC3 compiler which is going to use the flag:

hip_version_flat=500723341
Adding the -fno-offload-uniform-block compiler flag
