### ISSUE TITLE
CK backward weight kernel hanging 

### ISSUE THREAD

**Issue by iq136boy** [ROCm/composable_kernel#852]
We were integrated CK backward weight solver (kernel) into MIOpen. However, it seems that the CK kernel hanging. I back tracked the calling stacks and find it is hanging at hipEventSynchronize(), which means the kernel did not finish the work properly on GPU and caused the hanging.  The following are some configs that we used to run the test:
    g   n   c   d    h   w   k   z  y  x pad_x pad_y pad_z stri_x stri_y stri_z dia_x dia_y dia_z
    1, 128, 64, 14, 28, 28, 64, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1
    1, 64, 128, 28, 28, 3, 128, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1
     8, 64, 128, 28, 28, 3, 128, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1

**Comment by bartekxk** [comment]
Hello, I successfully ran Your tests cases:
```
 ################                   op   datatype  layout  verify  init  log  time  Ndims  G   N   K   C  Z Y  X D Hi  Wi  Sy  Sx  Dy  Dx  LeftPy  LeftPx  RightPy  RightPx  SplitK

./bin/ckProfiler grouped_conv_bwd_weight  0        1         0        1    0    1     3    1 128   64  64 3 3 3  14 28 28 1 1 1 1 1 1 1 1 1 1 1 1 1
./bin/ckProfiler grouped_conv_bwd_weight  0        1         0        1    0    1     3    1 64    128 128 3 3 3 28 28 3 1 1 1 1 1 1 1 1 1 1 1 1 1
./bin/ckProfiler grouped_conv_bwd_weight  0        1         0        1    0    1     3    8 64    128 128 3 3  3 28 28 3 1 1 1 1 1 1 1 1 1 1 1 1 1
```
Are my cases correct ? Which datatype, splitK value and layout do You use? Are you using the latest ck version? Do You have some more information?

**Comment by iq136boy** [comment]
Hi, may I ask what is the strides looks like when you run the first test case? Could you show me the strides, I mean the input strides, output strides and especially, the weight strides?

**Comment by iq136boy** [comment]
The issue was resolved using the latest ck commit hash. Close the issue. Thanks.
