### ISSUE TITLE
3D group backward data convolution still missing some instances

### ISSUE THREAD

**Issue by iq136boy** [ROCm/composable_kernel#872]
I ran the test with the latest CK commit hash for the 3d backward data and backward weight solvers that I just integrated into MIOpen. The backward weight solvers works fine after I raise the error tolerance for most of the cases. However, for some configurations, the backward data and backward weight solvers still can not find any instances. It seems that these instances do not add properly.

**Comment by zjing14** [comment]
@bartekxk

**Comment by bartekxk** [comment]
Hi, Can I ask for these cases?

**Comment by bartekxk** [comment]
Fixed by #876
