### ISSUE TITLE
Fused Attention Kernel with gfx1030?

### ISSUE THREAD

**Issue by onesnep** [ROCm/composable_kernel#886]
I was glad to see [Flash Attention ported to ROCM](https://github.com/ROCmSoftwarePlatform/flash-attention), however currently compatibility is limited to gfx90a. I and many others would love to see this on other architectures. 

When building Composable Kernel against a gfx1030 target I noticed that the fused attention examples were removed from the test cases. The docs [briefly mentioned partial compatibility for gfx1030](https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/develop/docs/tutorial_hello_world.rst), but I couldn't find concrete details about the differences in operator support between architectures.

I would appreciate clarification on whether a fused kernel suitable for Flash Attention would be possible on other architectures such as gfx1030 or even gfx1100, and if so, whether this is in the pipeline or else left to the community to implement.

Many thanks

**Comment by ThePerfectComputer** [comment]
I'm also curious about this - specifically about support for the gfx906 architecture.

**Comment by linchen111** [comment]
> I'm also curious about this - specifically about support for the gfx906 architecture.我对此也很好奇——特别是对 gfx906 架构的支持。

hello, I am curious about gfx906 too, did you have it already

**Comment by jamesxu2** [comment]
Hello @onesnep @ThePerfectComputer @linchen111 , 

Composable kernel does not support Flash Attention on other architectures at the moment - only [recent Instinct devices](https://github.com/ROCm/composable_kernel/blob/develop/docs/tutorial/tutorial_hello_world.rst#hardware-targets). None of the architectures that are mentioned in the comments here (gfx1030, gfx1100, gfx906) support FA.

However, your comments are heard by the composable kernel team. They are aware of requests to port FA to other architectures and this task is in the pipeline, though we unfortunately can't give you a more specific timeline at the moment. 

Thanks for your feedback!

**Comment by jamesxu2** [comment]
Hi @onesnep, 

I just wanted to update that there is now a PR in upstream FlashAttention: https://github.com/Dao-AILab/flash-attention/pull/1203 as a step towards this feature.

**Comment by Said-Akbar** [comment]
Hello @jamesxu2 ,

[#Dao-AILab/flash-attention/pull/1203](https://github.com/Dao-AILab/flash-attention/pull/1203#issuecomment-2447599962) says it does not support archs below MI100. So, basically triton compiler will not work or is not optimized for gfx906 (AMD MI50/60 cards).
Can you please share if there is a plan to support gfx906 cards for CK Flash Attention? There are many thousands of users with MI50/60/Radeon VII cards that want to use CK Flash Attention and your team can make it reality. 
Please, let me know. 
Thanks!

**Comment by emircanerkul** [comment]
Great! closed as wont do :)

**Comment by YellowRoseCx** [comment]
fused attention is now supported on gfx1030 using the ROCM flash-attention Triton backend on the developer branch of their FA repo

https://github.com/ROCm/flash-attention/tree/main_perf/flash_attn/flash_attn_triton_amd

**Comment by derfasthirnlosenick** [comment]
> fused attention is now supported on gfx1030 using the ROCM flash-attention Triton backend on the developer branch of their FA repo
> 
> https://github.com/ROCm/flash-attention/tree/main_perf/flash_attn/flash_attn_triton_amd

hm didn't get it to work - did you manage to following the process laid out there?

edit: got it to work seemingly - pytest still fails (can't find torch) but ComfyUI allows --use-flash-attention. It's slower than quad-attention though.
