### ISSUE TITLE
Fix  GetWorkspaceSize() in some device operator 

### ISSUE THREAD

**Issue by qianfengz** [ROCm/composable_kernel#911]
Just found that

1. `/data/composable_kernel/include/ck/tensor_operation/gpu/device/device_cgemm.hpp` defined `GetWorkspaceSize`
2. `/data/composable_kernel/include/ck/tensor_operation/gpu/device/impl/device_cgemm_4gemm_xdl_cshuffle.hpp` implemented `GetWorkspaceSize`

The correct name should be `GetWorkSpaceSize`

**Comment by ppanchad-amd** [comment]
@qianfengz Is this fixed in the latest ROCm 6.2? If so, please close the ticket. Thanks!

**Comment by zichguan-amd** [comment]
Hi @qianfengz, the fix has been merged, closing the issue.
