### ISSUE TITLE
what's difference between dl, xdl and wmma in /example/01_gemm

### ISSUE THREAD

**Issue by EzioZz** [ROCm/composable_kernel#924]
Hi,
I have three questions
1.what's difference between dl, xdl and wmma in /example/01_gemm
![image](https://github.com/ROCmSoftwarePlatform/composable_kernel/assets/22981348/c805b7df-2c93-4d01-b2a5-7adcd658e9cb)
2. Will composable kernel call openblas or rocblas on cpu?

**Comment by wsippel** [comment]
wmma uses the Radeon 7000 series AI accelerators, whereas xdl uses MI200 and MI300 series Matrix cores I believe.

**Comment by EzioZz** [comment]
thx

**Comment by alohali** [comment]
> wmma uses the Radeon 7000 series AI accelerators, whereas xdl uses MI200 and MI300 series Matrix cores I believe.

What about dpp and dl ?
